
var baseData = {
  "category_id": null,
  "type_json": "",
  "knowledge_set_id":"",
  "dy_hot_one_like_name": "",
  "dy_hot_one_like_img": "",
  "dy_hot_one_like_fans_num": "",
  "dy_hot_one_like_like_num": "",
  "dy_hot_one_comment_name": "",
  "dy_hot_one_comment_img": "",
  "dy_hot_one_comment_fans_num": "",
  "dy_hot_one_comment_comment_num": "",
  "dy_hot_one_share_name": "",
  "dy_hot_one_share_img": "",
  "dy_hot_one_share_fans_num": "",
  "dy_hot_one_share_share_num": "",
  "ks_hot_one_like_name": "",
  "ks_hot_one_like_img": "",
  "ks_hot_one_like_fans_num": "",
  "ks_hot_one_like_like_num": "",
  "ks_hot_one_comment_name": "",
  "ks_hot_one_comment_img": "",
  "ks_hot_one_comment_fans_num": "",
  "ks_hot_one_comment_comment_num": "",
  "ks_hot_one_share_name": "",
  "ks_hot_one_share_img": "",
  "ks_hot_one_share_fans_num": "",
  "ks_hot_one_share_share_num": "",
  "dy_top_three_like_one_name": "",
  "dy_top_three_like_one_auhor": "",
  "dy_top_three_like_one_title": "",
  "dy_top_three_like_one_like_num": "",
  "dy_top_three_like_one_analysis": "",
  "dy_top_three_like_one_links": "",
  "dy_top_three_like_two_name": "",
  "dy_top_three_like_two_auhor": "",
  "dy_top_three_like_two_title": "",
  "dy_top_three_like_two_like_num": "",
  "dy_top_three_like_two_analysis": "",
  "dy_top_three_like_two_links": "",
  "dy_top_three_like_three_name": "",
  "dy_top_three_like_three_auhor": "",
  "dy_top_three_like_three_title": "",
  "dy_top_three_like_three_like_num": "",
  "dy_top_three_like_three_analysis": "",
  "dy_top_three_like_three_links": "",
  "dy_top_three_comment_one_name": "",
  "dy_top_three_comment_one_auhor": "",
  "dy_top_three_comment_one_title": "",
  "dy_top_three_comment_one_like_num": "",
  "dy_top_three_comment_one_analysis": "",
  "dy_top_three_comment_one_links": "",
  "dy_top_three_comment_two_name": "",
  "dy_top_three_comment_two_auhor": "",
  "dy_top_three_comment_two_title": "",
  "dy_top_three_comment_two_like_num": "",
  "dy_top_three_comment_two_analysis": "",
  "dy_top_three_comment_two_links": "",
  "dy_top_three_comment_three_name": "",
  "dy_top_three_comment_three_auhor": "",
  "dy_top_three_comment_three_title": "",
  "dy_top_three_comment_three_like_num": "",
  "dy_top_three_comment_three_analysis": "",
  "dy_top_three_comment_three_links": "",
  "dy_top_three_share_one_name": "",
  "dy_top_three_share_one_auhor": "",
  "dy_top_three_share_one_title": "",
  "dy_top_three_share_one_like_num": "",
  "dy_top_three_share_one_analysis": "",
  "dy_top_three_share_one_links": "",
  "dy_top_three_share_two_name": "",
  "dy_top_three_share_two_auhor": "",
  "dy_top_three_share_two_title": "",
  "dy_top_three_share_two_like_num": "",
  "dy_top_three_share_two_analysis": "",
  "dy_top_three_share_two_links": "",
  "dy_top_three_share_three_name": "",
  "dy_top_three_share_three_auhor": "",
  "dy_top_three_share_three_title": "",
  "dy_top_three_share_three_like_num": "",
  "dy_top_three_share_three_analysis": "",
  "dy_top_three_share_three_links": "",
  "ks_top_three_like_one_name": "",
  "ks_top_three_like_one_auhor": "",
  "ks_top_three_like_one_title": "",
  "ks_top_three_like_one_like_num": "",
  "ks_top_three_like_one_analysis": "",
  "ks_top_three_like_one_links": "",
  "ks_top_three_like_two_name": "",
  "ks_top_three_like_two_auhor": "",
  "ks_top_three_like_two_title": "",
  "ks_top_three_like_two_like_num": "",
  "ks_top_three_like_two_analysis": "",
  "ks_top_three_like_two_links": "",
  "ks_top_three_like_three_name": "",
  "ks_top_three_like_three_auhor": "",
  "ks_top_three_like_three_title": "",
  "ks_top_three_like_three_like_num": "",
  "ks_top_three_like_three_analysis": "",
  "ks_top_three_like_three_links": "",
  "ks_top_three_comment_one_name": "",
  "ks_top_three_comment_one_auhor": "",
  "ks_top_three_comment_one_title": "",
  "ks_top_three_comment_one_like_num": "",
  "ks_top_three_comment_one_analysis": "",
  "ks_top_three_comment_one_links": "",
  "ks_top_three_comment_two_name": "",
  "ks_top_three_comment_two_auhor": "",
  "ks_top_three_comment_two_title": "",
  "ks_top_three_comment_two_like_num": "",
  "ks_top_three_comment_two_analysis": "",
  "ks_top_three_comment_two_links": "",
  "ks_top_three_comment_three_name": "",
  "ks_top_three_comment_three_auhor": "",
  "ks_top_three_comment_three_title": "",
  "ks_top_three_comment_three_like_num": "",
  "ks_top_three_comment_three_analysis": "",
  "ks_top_three_comment_three_links": "",
  "ks_top_three_share_one_name": "",
  "ks_top_three_share_one_auhor": "",
  "ks_top_three_share_one_title": "",
  "ks_top_three_share_one_like_num": "",
  "ks_top_three_share_one_analysis": "",
  "ks_top_three_share_one_links": "",
  "ks_top_three_share_two_name": "",
  "ks_top_three_share_two_auhor": "",
  "ks_top_three_share_two_title": "",
  "ks_top_three_share_two_like_num": "",
  "ks_top_three_share_two_analysis": "",
  "ks_top_three_share_two_links": "",
  "ks_top_three_share_three_name": "",
  "ks_top_three_share_three_auhor": "",
  "ks_top_three_share_three_title": "",
  "ks_top_three_share_three_like_num": "",
  "ks_top_three_share_three_analysis": "",
  "ks_top_three_share_three_links": "",
  "dy_today_hop_keywords": "",
}



export  function initData(data){
   var baseData = {
        /**
         * 分类id和数量 集合
         */
        "category_id": null,
        "type_json": "",  //图表数据
        "knowledge_set_id":"",

        /**
         * 抖音热门三类第一
         */
        "dy_hot_one_like_name": data.dy.like[0].author,
        "dy_hot_one_like_img": data.dy.like[0].img,
        "dy_hot_one_like_fans_num": "",
        "dy_hot_one_like_like_num": data.dy.like[0].like_num,

        "dy_hot_one_comment_name": data.dy.comment[0].author,
        "dy_hot_one_comment_img": data.dy.comment[0].img,
        "dy_hot_one_comment_fans_num": "",
        "dy_hot_one_comment_comment_num": data.dy.comment[0].comment_num,

        "dy_hot_one_share_name": data.dy.share[0].author,
        "dy_hot_one_share_img":data.dy.share[0].img,
        "dy_hot_one_share_fans_num": "",
        "dy_hot_one_share_share_num": data.dy.share[0].share_num,

        /**
         * 快手热门三类第一
         */
        "ks_hot_one_like_name": data.ks.like[0].author,
        "ks_hot_one_like_img": data.ks.like[0].img,
        "ks_hot_one_like_fans_num": "",
        "ks_hot_one_like_like_num": data.dy.like[0].like_num,

        "ks_hot_one_comment_name": data.ks.comment[0].author,
        "ks_hot_one_comment_img": data.ks.comment[0].img,
        "ks_hot_one_comment_fans_num": "",
        "ks_hot_one_comment_comment_num": data.dy.comment[0].comment_num,

        "ks_hot_one_share_name": data.ks.share[0].author,
        "ks_hot_one_share_img": data.ks.share[0].img,
        "ks_hot_one_share_fans_num": "",
        "ks_hot_one_share_share_num": data.dy.share[0].share_num,

        /**
         * 抖音top3
         */
        "dy_top_three_like_one_name":  "",
        "dy_top_three_like_one_auhor":  data.dy.like[0].author,
        "dy_top_three_like_one_title":  data.dy.like[0].title,
        "dy_top_three_like_one_like_num":  data.dy.like[0].like_num,
        "dy_top_three_like_one_analysis": "",
        "dy_top_three_like_one_links":  data.dy.like[0].share_link,

        "dy_top_three_like_two_name":  "",
        "dy_top_three_like_two_auhor":  data.dy.like[1].author,
        "dy_top_three_like_two_title":  data.dy.like[1].title,
        "dy_top_three_like_two_like_num":  data.dy.like[1].like_num,
        "dy_top_three_like_two_analysis": "",
        "dy_top_three_like_two_links":  data.dy.like[1].share_link,

        "dy_top_three_like_three_name":  "",
        "dy_top_three_like_three_auhor":  data.dy.like[2].author,
        "dy_top_three_like_three_title":  data.dy.like[2].title,
        "dy_top_three_like_three_like_num":  data.dy.like[2].like_num,
        "dy_top_three_like_three_analysis": "",
        "dy_top_three_like_three_links":  data.dy.like[2].share_link,

        "dy_top_three_comment_one_name":  "",
        "dy_top_three_comment_one_auhor":  data.dy.comment[0].author,
        "dy_top_three_comment_one_title":  data.dy.comment[0].title,
        "dy_top_three_comment_one_comment_num":  data.dy.comment[0].comment_num,
        "dy_top_three_comment_one_analysis": "",
        "dy_top_three_comment_one_links":  data.dy.comment[0].share_link,

        "dy_top_three_comment_two_name":  "",
        "dy_top_three_comment_two_auhor":  data.dy.comment[1].author,
        "dy_top_three_comment_two_title":  data.dy.comment[1].title,
        "dy_top_three_comment_two_comment_num":  data.dy.comment[1].comment_num,
        "dy_top_three_comment_two_analysis": "",
        "dy_top_three_comment_two_links":  data.dy.comment[1].share_link,

        "dy_top_three_comment_three_name":  "",
        "dy_top_three_comment_three_auhor":  data.dy.comment[2].author,
        "dy_top_three_comment_three_title":  data.dy.comment[2].title,
        "dy_top_three_comment_three_comment_num":  data.dy.comment[2].comment_num,
        "dy_top_three_comment_three_analysis": "",
        "dy_top_three_comment_three_links":  data.dy.comment[2].share_link,

        "dy_top_three_share_one_name":  "",
        "dy_top_three_share_one_auhor":  data.dy.share[0].author,
        "dy_top_three_share_one_title":  data.dy.share[0].title,
        "dy_top_three_share_one_share_num":  data.dy.share[0].share_num,
        "dy_top_three_share_one_analysis": "",
        "dy_top_three_share_one_links":  data.dy.share[0].share_link,

        "dy_top_three_share_two_name":  "",
        "dy_top_three_share_two_auhor":  data.dy.share[1].author,
        "dy_top_three_share_two_title":  data.dy.share[1].title,
        "dy_top_three_share_two_share_num":  data.dy.share[1].share_num,
        "dy_top_three_share_two_analysis": "",
        "dy_top_three_share_two_links":  data.dy.share[1].share_link,

        "dy_top_three_share_three_name":  "",
        "dy_top_three_share_three_auhor":  data.dy.share[2].author,
        "dy_top_three_share_three_title":  data.dy.share[2].title,
        "dy_top_three_share_three_share_num":  data.dy.share[2].share_num,
        "dy_top_three_share_three_analysis": "",
        "dy_top_three_share_three_links":  data.dy.share[2].share_link,


        /**
         * 快手部分 
         */
        "ks_top_three_like_one_name":  "",
        "ks_top_three_like_one_auhor":  data.ks.like[0].author,
        "ks_top_three_like_one_title":  data.ks.like[0].title,
        "ks_top_three_like_one_like_num":  data.ks.like[0].like_num,
        "ks_top_three_like_one_analysis": "",
        "ks_top_three_like_one_links":  data.ks.like[0].share_link,

        "ks_top_three_like_two_name":  "",
        "ks_top_three_like_two_auhor":  data.ks.like[1].author,
        "ks_top_three_like_two_title":  data.ks.like[1].title,
        "ks_top_three_like_two_like_num":  data.ks.like[1].like_num,
        "ks_top_three_like_two_analysis": "",
        "ks_top_three_like_two_links":  data.ks.like[1].share_link,

        "ks_top_three_like_three_name":  "",
        "ks_top_three_like_three_auhor":  data.ks.like[2].author,
        "ks_top_three_like_three_title":  data.ks.like[2].title,
        "ks_top_three_like_three_like_num":  data.ks.like[2].like_num,
        "ks_top_three_like_three_analysis": "",
        "ks_top_three_like_three_links":  data.ks.like[2].share_link,

        "ks_top_three_comment_one_name":  "",
        "ks_top_three_comment_one_auhor":  data.ks.comment[0].author,
        "ks_top_three_comment_one_title":  data.ks.comment[0].title,
        "ks_top_three_comment_one_comment_num":  data.ks.comment[0].comment_num,
        "ks_top_three_comment_one_analysis": "",
        "ks_top_three_comment_one_links":  data.ks.comment[0].share_link,

        "ks_top_three_comment_two_name":  "",
        "ks_top_three_comment_two_auhor":  data.ks.comment[1].author,
        "ks_top_three_comment_two_title":  data.ks.comment[1].title,
        "ks_top_three_comment_two_comment_num":  data.ks.comment[1].comment_num,
        "ks_top_three_comment_two_analysis": "",
        "ks_top_three_comment_two_links":  data.ks.comment[1].share_link,

        "ks_top_three_comment_three_name":  "",
        "ks_top_three_comment_three_auhor":  data.ks.comment[2].author,
        "ks_top_three_comment_three_title":  data.ks.comment[2].title,
        "ks_top_three_comment_three_comment_num":  data.ks.comment[2].comment_num,
        "ks_top_three_comment_three_analysis": "",
        "ks_top_three_comment_three_links":  data.ks.comment[2].share_link,

        "ks_top_three_share_one_name":  "",
        "ks_top_three_share_one_auhor":  data.ks.share[0].author,
        "ks_top_three_share_one_title":  data.ks.share[0].title,
        "ks_top_three_share_one_share_num":  data.ks.share[0].share_num,
        "ks_top_three_share_one_analysis": "",
        "ks_top_three_share_one_links":  data.ks.share[0].share_link,

        "ks_top_three_share_two_name":  "",
        "ks_top_three_share_two_auhor":  data.ks.share[1].author,
        "ks_top_three_share_two_title":  data.ks.share[1].title,
        "ks_top_three_share_two_share_num":  data.ks.share[1].share_num,
        "ks_top_three_share_two_analysis": "",
        "ks_top_three_share_two_links":  data.ks.share[1].share_link,

        "ks_top_three_share_three_name":  "",
        "ks_top_three_share_three_auhor":  data.ks.share[2].author,
        "ks_top_three_share_three_title":  data.ks.share[2].title,
        "ks_top_three_share_three_share_num":  data.ks.share[2].share_num,
        "ks_top_three_share_three_analysis": "",
        "ks_top_three_share_three_links":  data.ks.share[2].share_link,
         /**
          * 热搜排行榜前十
          */
        "dy_today_hop_keywords": "",
    }
    return baseData
}